blank_issues_enabled: false
contact_links:
  - name: TFG-RetChanges Issues
    url: https://github.com/Ret-Samphis/TFG-RetChanges/issues
    about: Report issues specific to this fork.

  - name: TerraFirmaGreg-Modern (Original Pack)
    url: https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues
    about: For issues that also exist in the base pack.
